Space-Travelers-Hub
abdessalem1998/Space-Travelers-Hub pull request #32
Opened 2022-02-03 18:39 UTC by abdessalem1998

In this pull request I need to review my code for making Space Travelers' Hub web app I divide my work as follows:

- [ ] Milestone1 (Setup project): In this pull request firstly I use it to check if the GitHub actions and linter checker are set correctly and later for submitting for review for setting up the project:

- Set up a React and Redux app.
- Structure application files using a "feature folder".
- Install Redux Logger and React Router.
- Setup linter checker.

- [ ] Milestone2 (Missions page): In this pull request I need to review my code for making the missions page of my Space Travelers' Hub in this part I did the following:

- Design the missions page using bootstrap
- Fetch data from the SpaceX API endpoints
- Dispatch an action to store the selected data in the Redux store and display it.
- Write actions and reducers for joining missions.
- Write actions and reducers for canceling leaving missions

- [ ] Milestone3 (Rockets page): In this pull request I need to review my code for making the Rockets  page of my Space Travelers' Hub in this part I did the following:

- Design the Rockets page using bootstrap.
- Fetch data from the SpaceX API endpoints.
- Dispatch an action to store the selected data in the Redux store and display it.
- Write actions and reducers for reserving Rockets.
- Write actions and reducers for canceling Rockets.

- [ ]  Milestone4 (Profile): In this pull request I need to review my code for making the profile page of my Space Travelers' Hub in this part I did the following:

- Design the profile page using bootstrap.
- Filter the reserved Rockets and joined missions and display it in the profile.

2022-02-03 19:21 UTC, BrianSammit requested changes
# CHANGES REQUIRED 🔴 🛑
Hello @abdessalem1998 and @vic778, great job you are doing so far in this project. 💯

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- Great job with the design 

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️
See my inline comment to know what changes are needed. 👇 👀 

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![tenor-1](https://user-images.githubusercontent.com/64173189/152413916-e572a30e-0386-4f04-bc62-557115208096.gif)



**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-03 19:21 UTC, BrianSammit commented on src/App.js
> +import Rockets from './pages/Rockets';
- [x] You are importing the Rockets module twice. This is giving an error. 

![Capture](https://user-images.githubusercontent.com/64173189/152409663-d9da7fc3-c66b-4b1e-a556-188d5f441614.JPG)

Kindly fix this minor issue. 😄 💪

2022-02-03 19:21 UTC, BrianSammit commented on src/components/Header.js
> +        </NavLink>
- [ ] It would be better if the underline only shows on the active page link, currently, all the links have an underline. 

Please fix this 😄 👍

2022-02-03 19:21 UTC, BrianSammit commented on src/App.js
> +      </Routes>
- [ ] When I start the app the page does not show me anything. 

![Capture](https://user-images.githubusercontent.com/64173189/152412428-2310a54f-e04e-48fc-8a17-6babd4fa49e6.JPG)

Remember that when you start the app it must show the Rockets as a default view. 

![Capture](https://user-images.githubusercontent.com/64173189/152412649-bdfe69f2-7a50-408a-b1b6-1dbea7d336f0.JPG)

You could fix this minor issue just by changing the path of the rockets  

```suggestion
      <Routes>
        <Route path="/profile" element={<MyProfile />} />
        <Route path="/missions" element={<Missions />} />
        <Route path="/" element={<Rockets />} />
      </Routes>
```

Don't forget to change also the path of the navbar. 👍 💯

2022-02-03 19:21 UTC, BrianSammit commented on src/pages/Rocket.js
> +export default Rockets;
- [ ] You have this extra module that you are not using. Please delete this file. 💪 👏

2022-02-03 19:21 UTC, BrianSammit commented on README.md
> +
- [ ] Please add the steps about how to clone your repo. Remember to write these steps thinking on someone that doesn't know anything about programming. 💯 😃

2022-02-04 11:05 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Dib, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-04 14:19 UTC, merged